<?php

return [
    'roles' => [
        'super-admin' => [
            'name' => 'Super Admin',
            'description' => 'Full system access',
            'permissions' => ['*'],
        ],
        'admin' => [
            'name' => 'Admin',
            'description' => 'Operational administration access',
            'permissions' => [
                'users.view',
                'users.manage',
                'roles.view',
                'roles.assign',
                'clients.view',
                'clients.manage',
                'family.view',
                'family.manage',
                'caregivers.view',
                'caregivers.manage',
                'services.view',
                'services.manage',
                'bookings.view',
                'bookings.manage',
                'bookings.assign',
                'calendar.view',
                'payments.view',
                'payments.manage',
                'refunds.manage',
                'invoices.view',
                'visits.view',
                'visits.review',
                'messages.view',
                'messages.manage',
                'notifications.view',
                'ratings.view',
                'support.view',
                'support.manage',
                'reports.view',
                'reports.export',
                'settings.view',
                'settings.manage',
                'audit.view',
            ],
        ],
        'caregiver' => [
            'name' => 'Caregiver',
            'description' => 'Caregiver portal access',
            'permissions' => [
                'profile.view',
                'profile.update',
                'bookings.view.assigned',
                'calendar.view.own',
                'availability.manage.own',
                'visits.manage.assigned',
                'messages.view',
                'messages.create',
                'notifications.view',
                'ratings.view.own',
                'support.create',
                'support.view.own',
            ],
        ],
        'client' => [
            'name' => 'Client',
            'description' => 'Client booking and payment access',
            'permissions' => [
                'profile.view',
                'profile.update',
                'services.view',
                'bookings.create',
                'bookings.view.own',
                'bookings.manage.own',
                'payments.create',
                'payments.view.own',
                'invoices.view.own',
                'messages.view',
                'messages.create',
                'notifications.view',
                'ratings.create',
                'ratings.view.own',
                'support.create',
                'support.view.own',
            ],
        ],
        'family-member' => [
            'name' => 'Family Member',
            'description' => 'Family portal access',
            'permissions' => [
                'profile.view',
                'profile.update',
                'bookings.view.family',
                'invoices.view.family',
                'visits.view.family',
                'messages.view',
                'messages.create',
                'notifications.view',
                'support.create',
                'support.view.own',
            ],
        ],
    ],
];
